### ISSUE TITLE
Null values

### ISSUE THREAD

**Issue by tobia** [jameskleeh/groovy-excel-builder#13]
Null values currently trigger a NPE:

	java.lang.NullPointerException: Cannot get property 'class' on null object
		at com.jameskleeh.excel.internal.CreatesCells.cell(CreatesCells.groovy:190)
		at com.jameskleeh.excel.internal.CreatesCells.cell(CreatesCells.groovy:176)
		at com.jameskleeh.excel.Sheet$_row_closure1$_closure2.doCall(Sheet.groovy:139)
		at com.jameskleeh.excel.Sheet$_row_closure1.doCall(Sheet.groovy:138)
		at com.jameskleeh.excel.Sheet.row(Sheet.groovy:178)
		at com.jameskleeh.excel.Sheet.row(Sheet.groovy:151)
		at com.jameskleeh.excel.Sheet.row(Sheet.groovy:137)
		...

Maybe they should just be left as empty cells?

**Comment by jameskleeh** [comment]
Fixed by https://github.com/jameskleeh/groovy-excel-builder/commit/40767f0acbd4cf20e9d467c8bda3984dda878f1f
