### ISSUE TITLE
 javax.xml.stream.FactoryConfigurationError

### ISSUE THREAD

**Issue by JeanParfaitMKirwa** [jameskleeh/groovy-excel-builder#18]
I am new Groovy Excel Builder 

i am having problem even at the beginning of tutorial  with an exception:

> Caught: javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found
javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found
	at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41)
	at org.apache.poi.openxml4j.opc.OPCPackage.init(OPCPackage.java:161)
	at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:141)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:72)
	at org.apache.poi.openxml4j.opc.OPCPackage.create(OPCPackage.java:394)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.newPackage(XSSFWorkbook.java:475)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:243)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:235)
	at com.jameskleeh.excel.ExcelBuilder.build(ExcelBuilder.groovy:51)
	at com.jameskleeh.excel.ExcelBuilder.output(ExcelBuilder.groovy:40)
	at com.jameskleeh.excel.ExcelBuilder$output.call(Unknown Source)
	at main.groovy.FabricExcelTest.run(FabricExcelTest.groovy:10)

> 

and my code is simple 👍  as in introduction of the DSL :

> 
import com.jameskleeh.excel.ExcelBuilder

File file = new File('test.xlsx')

ExcelBuilder.output(new FileOutputStream(file)) {
    sheet {
        row("test")
    }
}

>

**Comment by JeanParfaitMKirwa** [comment]
I am not programming for android neither it is just a  groovy script

**Comment by jameskleeh** [comment]
Try adding `compile group: 'javax.xml.stream', name: 'stax-api', version: '1.0-2'`

**Comment by barrynorman** [comment]
Same for me. I added stax-api but didn't help. Any other suggestions?

**Comment by jameskleeh** [comment]
@barrynorman @JeanParfaitMKirwa If you can upload a sample project I'd be happy to take a look

**Comment by ngvtsn** [comment]
If you want to use `com.sun.xml.internal.stream.events.XMLEventFactoryImpl` from JDK, you have to exclude stax-api library
 `compile('com.jameskleeh:excel-builder:0.4.2') {
        exclude module: 'stax-api'
  }`
Or you can add `compile group: 'stax', name: 'stax', version: '1.2.0'`
Work for me.

**Comment by chuck-wood** [comment]
Sorry, where do I put those lines?
